backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path("", include('main.urls')),
    path("routesetting/", include("routesetting.urls")),
    #path('testing/', include("model_testing.urls")),
    path('admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()

main/urls.py
from django.urls import path
from main import views

urlpatterns = [
    path("", views.home, name = "home"),
    path("feedback/",views.give_feedback, name="feedback")
]

routesetting/urls.py
from django.urls import path
from routesetting import views
# from routesetting.models import Route

urlpatterns = [
    path("", views.home, name = "routesetting_home"),
    path("create_route/", views.create_route, name="new_route"),
    path("edit_route/<route_id>", views.edit_route, name="edit_route"),
    path("delete_route/<route_id>", views.delete_route, name="delete_route"),
    path("view_routes/", views.view_routes, name="view_routes"),
    path("import_routes/", views.import_routes_view, name="import routes"),
    path("nico/", views.nico, name="nico"),
]

routesetting/models.py
from django.db import models
from django import forms
from django.utils import timezone
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
import math

class Route(models.Model):
    location = models.PositiveSmallIntegerField(null=True,blank=True)
    type = models.CharField(max_length=1)
    grade_num = models.IntegerField()
        
    color_lookup = {
        "R":"D22B2B",
        "O":"FF5F1F",
        "Y":"FFEA00",
        "LG":"AAFF00",
        "DG":"355E3B",
        "Bu":"4169E1",
        "Pu":"9400D3",
        "Bk":"333333",
        "Pi":"FF00FF",
        "W":"DDDDDD",
    }
    class Colors(models.TextChoices):
        RED =         "R", "Red"
        ORANGE =      "O", "Orange"
        YELLOW =      "Y", "Yellow"
        LIGHT_GREEN = "LG", "Light green"
        DARK_GREEN =  "DG", "Dark green"
        BLUE =        "Bu", "Blue"
        PURPLE =      "Pu", "Purple"
        BLACK =       "Bk", "Black"
        PINK =        "Pi", "Pink"
        WHITE =       "W", "White"
    color = models.CharField(
        max_length = 2,
        choices = Colors.choices,
        default = Colors.RED
    )
    name = models.CharField(max_length=100)
    class Setters(models.TextChoices):
        KB = "K", "KB"
        APE = "A", "APE"
        OK = "O", "OK"
        TOPS = "T", "TOPS"
        FIREWX = "F", "firewx"
        MERM = "M", "Merm"
        SUNNY = "S", "Sunny"
        CHALK = "C", "Chalk Snorter"
        MAC = "MD", "McDeee"
        TBEAR = "TB", "TBear"
        STEELTOES = "ST", "Steel toes"
        BLACKBEAR = "B", "Blackbear"
    setter = models.CharField(
        max_length=2,
        choices = Setters.choices,
        default = Setters.KB,
    )
    date_set = models.DateField()
    date_logged = models.DateTimeField()
    archived = models.BooleanField()
    archived_date = models.DateTimeField(null=True)

    @property
    def grade(self):
        if self.type == "T":
            pre = "5."
        elif self.type == "B":
            pre = "V"
        else:
            pre = "invalid route type"

        mod = self.grade_num%10
        if mod < 5:
            return pre + str(int(self.grade_num/10))+"+"*mod
        elif mod == 5:
            return pre + "fuck you"
        else:
            return pre + str(1+math.floor(self.grade_num/10))+"-"*(10-mod)

    def __str__(self) -> str:
        return "({}) {}".format(self.grade,self.name)
    
    class Meta:
        ordering = ['grade_num']
    
class RouteFeedback(models.Model):
    route = models.ForeignKey(Route, on_delete=models.CASCADE, blank=True, null=True)
    feedback = models.CharField(max_length=300, blank=True)
    rating = models.IntegerField(null=True, blank=True)
    grade_int = models.IntegerField(null=True, blank=True)
    date = models.DateTimeField()

    @property
    def grade(self):
        if self.route == None:
            return "None"
        if self.grade_int == None:
            return "bad feedback"
        
        if self.route.type == "T":
            pre = "5."
        elif self.route.type == "B":
            pre = "V"
        else:
            pre = "invalid route type"

        mod = self.grade_int%10
        if mod < 5:
            return pre + str(int(self.grade_int/10))+"+"*mod
        elif mod == 5:
            return pre + "fuck you"
        else:
            return pre + str(1+math.floor(self.grade_int/10))+"-"*(10-mod)

routesetting/forms.py
from typing import Any
from django import forms
from routesetting import models
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

class GradeNumField(forms.Field):
    # converts string to grade int (same for tr and boulder)
    def to_python(self, route_str):
        if route_str == '':
            return None

        if route_str[:2] == "5.":
            route_str = route_str[2:]
        elif route_str[:1].lower() == "v":
            route_str = route_str[1:]
        num = 0
        for char in route_str:
            if char.isdigit():
                num = num * 10 + int(char) * 10
            elif char == "+":
                num += 1
            elif char == "-":
                num -= 1
            else:
                raise ValidationError(
                    _("Unknown character %(value)s"),
                    code="invalid",
                    params={"value":char}
                )
        return num
    
    def validate(self, value: Any):
        super().validate(value)
        if value == None:
            return
        if value > 170:
            raise ValidationError(
                _("Grade too large: %(value)s"), 
                code="invalid",
                params={"value": value},
            )
        if value < -1:
            raise ValidationError(
                _("Grade too small: %(value)s"), 
                code="invalid",
                params={"value": value},
            )
    

class GradeTypeField(forms.CharField):
    def validate(self, value: Any):
        super().validate(value)
        if value != "T" and value != "B":
            raise ValidationError(
                _("Invalid route type: %(value)s"), 
                code="invalid",
                params={"value": value},
            )


class RouteForm(forms.ModelForm):
    type = GradeTypeField()
    grade = GradeNumField()

    def clean(self):
        super().clean()
        route_type = self.cleaned_data.get("route_type")
        raw_grade = self.data.get("grade")

        if route_type == "T" and raw_grade[0] == "V":
            raise ValidationError("Top rope grades can not start with V")
        if route_type == "B" and raw_grade[:2] == "5.":
            raise ValidationError("Boulder grades can not start with 5.")

    class Meta:
        model = models.Route
        fields = ("location", "color", "name", "setter", "date_set", "grade", "type")
            # "grade": GradeField,
        field_classes = {
            # "type": RouteTypeField,
        }

routesetting/views.py
from typing import Any
from django.shortcuts import render
from django.http import HttpResponse
from django.utils.timezone import datetime
from django.shortcuts import redirect

from routesetting.models import Route
from routesetting.forms import RouteForm

from operator import itemgetter

from routesetting.import_routes import *

# Create your views here.

def home(request):
    return render(request, "routesetting/home.html")

def get_routes_list(type):
    return list(Route.objects.filter(archived__exact=False, type=type).order_by('color').values_list("grade_num", "color", "name"))

def delete_route(request, route_id):
    Route.objects.filter(id=route_id).delete()
    return redirect("view_routes")

def view_routes(request):
    # if request.method == "POST":
    #     Route.objects.filter(id=request.POST['delete']).delete()
    if request.user_agent.is_mobile:
        print("hon hon hor ")
    context = {}
    context['tr_obj'] = Route.objects.filter(archived__exact=False, type="T").order_by("grade_num")
    context['b_obj'] = Route.objects.filter(archived__exact=False, type="B").order_by("grade_num")
    context['color_lookup'] = Route.color_lookup
    context['b_list'] = get_routes_list('B')
    context['tr_list'] = get_routes_list('T')
    return render(request, "routesetting/view_routes.html", context)

def create_route(request):
    form = RouteForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            route = form.save(commit=False)
            route.date_logged = datetime.now()
            route.archived = False
            route.save()
            return redirect("view_routes")
    return render(request, "routesetting/create_route.html", {"form": form})

def edit_route(request, route_id):
    route_base = Route.objects.get(id = route_id)
    initial = {"grade": route_base.grade}
    form = RouteForm(request.POST or None, instance=route_base, initial=initial)
    if request.method == "POST":
        if form.is_valid():
            form.save()
            return redirect("view_routes")
    return render(request, "routesetting/create_route.html", {"form": form})

def nico(request):
    form = RouteForm(None)
    return render(request, "routesetting/nico_home.html", {"form": form})

def import_routes_view(request):
    csv_file_path = '/Users/k1einbottle/Documents/code/Github/ClimbingSite/test.csv'  # Replace with your actual file path
    import_routes(csv_file_path)
    return redirect('view_routes')

routesetting/templates/routesetting/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    {% if request.user_agent.is_mobile %}
    <link rel="stylesheet" type="text/css" href="{% static 'routesetting/mobile.css' %}"/>
    {% else %}
    <link rel="stylesheet" type="text/css" href="{% static 'routesetting/site.css' %}"/>
    {% endif %}
    <link rel="shortcut icon" href="https://m.media-amazon.com/images/I/71vo-TtbyeL._AC_UF1000,1000_QL80_.jpg">
    <script src="https://cdn.plot.ly/plotly-2.34.0.min.js" charset="utf-8"></script>
</head>

<body>
<div class="navbar">
    <a href="{% url 'home' %}" class="navbar-brand">Home</a>
    <a href="{% url 'new_route' %}" class="navbar-item">Set</a>
    <a href="{% url 'view_routes' %}" class="navbar-item">Routes</a>
    {% comment %} <a href="{% url 'nico' %}" class="navbar-item">Nico</a> {% endcomment %}
    {% comment %} <a href="{% url 'import' %}" class="navbar-item">Import</a> {% endcomment %}
</div>

<div class="body-content">
    {% block content %}
    {% endblock %}
    <hr/>
    <footer>
        {% comment %} <p>&copy; 2024</p> {% endcomment %}
    </footer>
</div>

<script src="{% static 'routesetting/main.js' %}" data-home_url="{% url 'home' %}"></script> 

</body>
</html>

routesetting/templates/routesetting/templates/route_graphs.html
<div class="parent graph-parent">
    <div id="boulder dist" class="child graph-child">
        <!-- grade dist chart will be made by js -->
    </div>
    <div id="toprope dist" class="child graph-child">
        <!-- grade dist chart will be made by js -->
    </div>
</div>

{{ tr_list|json_script:"tr_list" }}
{{ b_list|json_script:"b_list"}}
{{ color_lookup|json_script:"color_lookup" }}

routesetting/templates/routesetting/templates/routelist.html
<div>
    <h2>{{route_type}}</h2>

    {% if route_list %}
    <table class="route_list">
        <thead>
            <tr>
                <th>Grade</th>
                <th>Name</th>
                <th>Setter</th>
                <th>Color</th>
                <th>Edit</th>
                {% comment %} <th>Archive</th> {% endcomment %}
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            {% for route in route_list %}
            <tr>
                <td>{{ route.grade }}</td>
                <td>{{ route.name }}</td>
                <td>{{ route.get_setter_display }}</td>
                <td>{{ route.get_color_display }}</td>
                <td><button id="e{{route.id}}" onclick="edit_route(this.id)">Edit</button></td>
                {% comment %} <td><button id="a{{route.id}}" onclick="archive_route(this.id)">Archive</button></td> {% endcomment %}
                <td><button id="d{{route.id}}" onclick="delete_route(this.id)">Delete</button></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <p>No {{route_type}}s have been set. Use the <a href="{% url 'new_route' %}">set route</a> page.</p>
    {% endif %}
</div>